FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    --timeout 300 \
    --retries 5

ARG CACHE_BUST=unknown
RUN echo "$CACHE_BUST" > /dev/null

COPY . .

RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE 8501

ENV MODEL_PATH=/app/models/price_tier_classifier_v1.pkl
ENV RECOMMENDER_PATH=/app/models/recommender_index.pkl
ENV CATEGORY_MODEL_PATH=/app/models/category_classifier_v1.pkl

ENV API_URL=https://pharmiq-api.redsand-37d94e81.eastus.azurecontainerapps.io

CMD ["streamlit", "run", "streamlit_app/app.py", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.headless=true"]